apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-events
spec:
  releaseName: argo-events
  chart:
    spec:
      chart: argo-events
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      version: "1.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3