apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terraform-operator
spec:
  releaseName: terraform-operator
  chart:
    spec:
      chart: terraform
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: kube-system
      version: "1.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: terraform-operator-values
