apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: terraformrc
  namespace: kube-system
spec:
  backendType: gcpSecretsManager
  # Project to use for GCP Secrets Manager (use the service account project by default)
  projectId: mcntrn-devops
  data:
    # Key in GCP Secrets Manager (without projet and version)
    - key: terraformrc
      # Key to use in Kubernetes secret (not the secret name, who is determined by metadata.name)
      name: credentials
