apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: workspacesecrets
  namespace: kube-system
spec:
  backendType: gcpSecretsManager
  # Project to use for GCP Secrets Manager (use the service account project by default)
  projectId: mcntrn-devops
  data:
    # Key in GCP Secrets Manager (without projet and version)
    - key: aws_access_key_id
      # Key to use in Kubernetes secret (not the secret name, who is determined by metadata.name)
      name: AWS_ACCESS_KEY_ID
      # If the secret is a valid JSON, try to get this property
    - key: aws_secret_access_key
      # Key to use in Kubernetes secret (not the secret name, who is determined by metadata.name)
      name: AWS_SECRET_ACCESS_KEY
