apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pi-hole
spec:
  releaseName: pi-hole
  chart:
    spec:
      chart: pi-hole
      sourceRef:
        kind: HelmRepository
        name: t3n
        namespace: flux-system
      version: "1.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: pi-hole-values
